version: '3.8'

services:

  rattlesnake_server:
    privileged: true
    build:
      context: ./server
      dockerfile: ./Dockerfile
    volumes:
      - ./server:/home
    ports:
      - 8080:8080
    env_file:
      - ./server/cfg.txt
    depends_on:
      - mariadb
    read_only: true
    restart: on-failure:10

  mariadb:
    image: mariadb:latest
    volumes:
      - ./mariadb:/var/lib/mysql
    env_file:
      - ./mariadb/mariadb_env.txt
    ports:
      - 3306:3306
    command: --max_allowed_packet=268435456
