name: CI
on: [pull_request]
jobs:
  Build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install env
        run: |
          sudo apt update
          sudo apt-get install libgtest-dev libgmock-dev lcov cmake make libbsd-dev valgrind cppcheck clang-tidy python clang-format libboost-all-dev qt5-default
          sudo pip install cpplint
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo git clone https://github.com/google/googletest.git
          cd googletest
          sudo mkdir build
          cd build
          sudo cmake .. -DBUILD_SHARED_LIBS=ON -DINSTALL_GTEST=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr
          sudo make -j8
          sudo make install
          sudo ldconfig
          cd ~
          wget https://github.com/sharkdp/hyperfine/releases/download/v1.4.0/hyperfine_1.4.0_amd64.deb
          sudo dpkg -i hyperfine_1.4.0_amd64.deb
          sudo apt install -f
      - name: build and test all
        run: sudo make
      - name: save server report artifact
        uses: actions/upload-artifact@v3
        with:
          name: report_server
          path: ./server/test/report_server/
      - name: save machine report artifact
        uses: actions/upload-artifact@v3
        with:
          name: report_machine
          path: ./server/test/report_machine/
      - name: save server application
        uses: actions/upload-artifact@v3
        with:
          name: RattlesnakeServer
          path: ./server/result_server_application/RattlesnakeServer
      - name: save machine application
        uses: actions/upload-artifact@v3
        with:
          name: RattlesnakeMachine
          path: ./server/result_machine/RattlesnakeMachine
