name: CI
on: [push, pull_request]
jobs:
  Build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Installation
        run: |
          sudo apt install gcc g++
          sudo apt-get install libgtest-dev cmake make
          cd /usr/src/googletest/googletest
          sudo mkdir build
          cd build
          sudo cmake ..
          sudo make
          sudo cp ./lib/libgtest*.a /usr/lib/
      - name: build
        run: |
          cd /home/runner/work/Rattlesnake/Rattlesnake/UI
          mkdir -p build
          cd build/
          sudo cmake ..
          sudo cmake --build .