name: CI
on: [push, pull_request]
jobs:
  Build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install env
        run: |
          sudo apt update
          sudo apt-get install libgtest-dev libgmock-dev lcov cmake make libbsd-dev valgrind cppcheck clang-tidy python clang-format libboost-all-dev
          sudo pip install cpplint
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp ./lib/libgtest*.a /usr/lib
          sudo cd /usr/src/googletest/googlemock/
          sudo mkdir build
          sudo cmake ..
          sudo make
          sudo cp googlemock/*.a /usr/lib
          cd ~
          wget https://github.com/sharkdp/hyperfine/releases/download/v1.4.0/hyperfine_1.4.0_amd64.deb
          sudo dpkg -i hyperfine_1.4.0_amd64.deb
          sudo apt install -f
      - name: build and test all
        run: sudo make
