name: CI
on: [push, pull_request]
jobs:
  Build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install env
        run: |
          sudo apt update
          sudo apt-get install libgtest-dev lcov cmake make libbsd-dev valgrind cppcheck clang-tidy python clang-format
          sudo pip install cpplint
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp ./lib/libgtest*.a /usr/lib
          cd ~
          wget https://github.com/sharkdp/hyperfine/releases/download/v1.4.0/hyperfine_1.4.0_amd64.deb
          sudo dpkg -i hyperfine_1.4.0_amd64.deb
          sudo apt install -f
      - name: build and test all
        run: sudo make
      - name: save report artifact
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: ./tests/report/
      - name: save speedtest artifact
        uses: actions/upload-artifact@v3
        with:
          name: speedtests
          path: ./tests/results/
